variable "region_name" {}
variable "cidr_address" {}
variable "vpc_tags" {}
variable "subnet_address" {}
variable "subnet1_tag" {}
variable "subnet2_address" {}
variable "subnet2_tag" {}
variable "subnet3_address" {}
variable "subnet3_tag" {}
variable "igw_tag" {}
variable "nat_tag" {}
variable "public_rt_address" {}
variable "private_cidr_address" {}
variable "private_rt_tag" {}
variable "sg_name" {}
variable "key_name" {}
variable "amazon_ami" {}
variable "redhat_ami" {}
variable "ubntu_ami" {}
